# Generated by Django 4.2.16 on 2025-08-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
