# Generated by Django 4.2.16 on 2025-08-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('POS', 'In-store (POS)')], db_index=True, default='ONLINE', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
