# Generated by Django 5.2.9 on 2026-03-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending (Waiting for Confirmation)"),
                    ("CONFIRMED", "Confirmed (Payment Pending)"),
                    ("READY", "Ready"),
                    ("RECEIVED", "Received"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
