# Generated by Django 4.2.16 on 2025-08-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_admin_receiver',
        ),
        migrations.AddField(
            model_name='device',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=16),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
