# Generated by Django 4.2.16 on 2025-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_static_path',
            field=models.CharField(blank=True, help_text='Path under static/, e.g. products/apple.jpg', max_length=255),
        ),
    ]
