# Generated by Django 4.2.16 on 2025-08-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_static_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_static_path',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
