# Generated by Django 4.2.16 on 2026-07-05 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0004_alter_category_name_alter_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delta",
                    models.IntegerField(
                        help_text="Signed change; negative = decrement."
                    ),
                ),
                ("balance_after", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("STOCKTAKE", "Stock-take upload"),
                            ("BULK_EDIT", "Bulk edit"),
                            ("SALE", "Sale"),
                            ("RETURN", "Return / restock"),
                            ("ADJUST", "Manual adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="products_st_product_3ae061_idx",
                    )
                ],
            },
        ),
    ]
