# Generated by Django 5.2.9 on 2026-07-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reserved",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
